export const API_ERROR = 'EVENT/API_ERROR_RECEIVED';

export const FETCH_WEATHER = 'COMMAND/FETCH_WEATHER_FOR_LAT_LNG';
export const WEATHER_DATA_RECEIVED = 'EVENT/WEATHER_DATA_RECEIVED';
export const WEATHER_ID_RECEIVED = 'EVENT/WEATHER_ID_RECEIVED';

export const INITIALIZE_LONG_POLLING = 'COMMAND/INITIALIZE_LONG_POLLING';
export const CONTINUE_LONG_POLLING = 'EVENT/CONTINUE_LONG_POLLING';

export const FETCH_DRONE = 'COMMAND/FETCH_DRONE';
export const DRONE_DATA_RECEIVED = 'EVENT/DRONE_DATA_RECEIVED';
export const DRONE_INCREMENT_LAST_RECEIVED =
  'EVENT/DRONE_INCREMENT_LAST_RECEIVED';
